### ISSUE TITLE
How this works exactly?

### ISSUE THREAD

**Issue by MichelDiz** [Phaze1D/parseDGraph#1]
It's some kind of middleware?
Can I use with Apollo?

Cheers

**Comment by Phaze1D** [comment]
Srry not at the moment haven't had the time to finish it but I'll get on it.

**Comment by MichelDiz** [comment]
But what would be the final purpose of this project? I'm interested in DGraph I met about 3 days ago.

**Comment by MichelDiz** [comment]
Will be like dgraphql?

**Comment by Phaze1D** [comment]
Pretty much the problem that I'm trying to solve is. Given a GraphQL AST, convert the AST into valid DGraph Query. 

Input - GraphQL AST object 
Output - DGraph Query string

So it's pretty much a custom DGraph Resolver for GraphQL
This should work with Apollo because it only depends on the GraphQL AST.

**Comment by MichelDiz** [comment]
This is perfect.

I am wanting to use GraphQL and now that I met the Dgraph I want to integrate it with GraphQL. I've tried Dgraphql, but it's not working with Apollo. Hence, I'm causing the resolvers to fetch the data by queries. One by one Is a work of typing...

**Comment by MichelDiz** [comment]
Hey, if you need me for tests just call!
I can try out diferentes environments to provoke bugs to solve. Different environments with different settings.

**Comment by Phaze1D** [comment]
Awesome I'll let you know when I finish the basic implementation
